name        : videoproto
version     : 2.3.3
release     : 5
source     :
    - http://xorg.freedesktop.org/releases/individual/proto/videoproto-2.3.3.tar.gz : df8dfeb158767f843054248d020e291a2c40f7f5e0ac6d8706966686fee7c5c0
license     :
    - MIT
summary     : X Video Extension
component   : xorg.proto
patterns    : /
description : |
    This extension provides a protocol for a video output mechanism, mainly to rescale video playback in the video controller hardware.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
